name: actions2
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - pip:
        - absl-py==0.9.0
        - cachetools==4.1.1
        - chardet==3.0.4
        - future==0.18.2
        - fvcore==0.1.1.post20200716
        - google-auth==1.20.1
        - google-auth-oauthlib==0.4.1
        - grpcio==1.31.0
        - idna==2.10
        - markdown==3.2.2
        - matplotlib==3.3.0
        - mock==4.0.2
        - oauthlib==3.1.0
        - portalocker==2.0.0
        - protobuf==3.12.4
        - pyasn1==0.4.8
        - pyasn1-modules==0.2.8
        - pycocotools==2.0.1
        - pydot==1.4.1
        - pyqt5-sip==4.19.18
        - pyqtchart==5.12
        - pyqtwebengine==5.12.1
        - requests==2.24.0
        - requests-oauthlib==1.3.0
        - rsa==4.6
        - tabulate==0.8.7
        - tensorboard==2.3.0
        - tensorboard-plugin-wit==1.7.0
        - termcolor==1.1.0
        - tqdm==4.48.2
        - urllib3==1.25.10
        - werkzeug==1.0.1
        - yacs==0.1.8
